### ISSUE TITLE
How about keeping the original proportion by default?

### ISSUE THREAD

**Issue by tevino** [jhchen/ansize#6]
Hi @jhchen 

Thanks for the tool, it's fully accorded with my need, I appreciated that.

I found the output got seriously squeezed with images of relatively large height to width ratio.

Here's what makes it so:

https://github.com/jhchen/ansize/blob/2bd5c17967f572afb6e1538667c75b68844ad6eb/ansize.go#L25
https://github.com/jhchen/ansize/blob/2bd5c17967f572afb6e1538667c75b68844ad6eb/ansize.go#L44

The image height during the resizing is hardcoded to `width * 0.46`, but why `0.46`?

How about keeping the original proportion by passing `0` as height to `Resize`?

**Comment by jhchen** [comment]
I believe it had to do with the character width and height ratio of the font and I tweaked with the images I wanted to use to see what was the best result. Feel free to tweak yourself if you use a different one.
